// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal.proto

package com.tao.protobuf.message.internal;

public final class Internal {
  private Internal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code DestType}
   *
   * <pre>
   *GTransfer消息发往的目的地类型
   * </pre>
   */
  public enum DestType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Client = 1;</code>
     *
     * <pre>
     *发向客户端
     * </pre>
     */
    Client(0, 1),
    /**
     * <code>Gate = 2;</code>
     *
     * <pre>
     *发向Gate网关服务器
     * </pre>
     */
    Gate(1, 2),
    /**
     * <code>Auth = 3;</code>
     *
     * <pre>
     *发向Auth认证服务器
     * </pre>
     */
    Auth(2, 3),
    /**
     * <code>Logic = 4;</code>
     *
     * <pre>
     *发向Logic逻辑服务器
     * </pre>
     */
    Logic(3, 4),
    ;

    /**
     * <code>Client = 1;</code>
     *
     * <pre>
     *发向客户端
     * </pre>
     */
    public static final int Client_VALUE = 1;
    /**
     * <code>Gate = 2;</code>
     *
     * <pre>
     *发向Gate网关服务器
     * </pre>
     */
    public static final int Gate_VALUE = 2;
    /**
     * <code>Auth = 3;</code>
     *
     * <pre>
     *发向Auth认证服务器
     * </pre>
     */
    public static final int Auth_VALUE = 3;
    /**
     * <code>Logic = 4;</code>
     *
     * <pre>
     *发向Logic逻辑服务器
     * </pre>
     */
    public static final int Logic_VALUE = 4;


    public final int getNumber() { return value; }

    public static DestType valueOf(int value) {
      switch (value) {
        case 1: return Client;
        case 2: return Gate;
        case 3: return Auth;
        case 4: return Logic;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DestType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<DestType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DestType>() {
            public DestType findValueByNumber(int number) {
              return DestType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.tao.protobuf.message.internal.Internal.getDescriptor().getEnumTypes().get(0);
    }

    private static final DestType[] VALUES = values();

    public static DestType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private DestType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:DestType)
  }

  public interface GTransferOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .DestType dest = 1;
    /**
     * <code>required .DestType dest = 1;</code>
     *
     * <pre>
     *目的地
     * </pre>
     */
    boolean hasDest();
    /**
     * <code>required .DestType dest = 1;</code>
     *
     * <pre>
     *目的地
     * </pre>
     */
    com.tao.protobuf.message.internal.Internal.DestType getDest();

    // optional uint64 netId = 2;
    /**
     * <code>optional uint64 netId = 2;</code>
     *
     * <pre>
     *全局唯一netId
     * </pre>
     */
    boolean hasNetId();
    /**
     * <code>optional uint64 netId = 2;</code>
     *
     * <pre>
     *全局唯一netId
     * </pre>
     */
    long getNetId();

    // required string userId = 3;
    /**
     * <code>required string userId = 3;</code>
     *
     * <pre>
     *用户Id
     * </pre>
     */
    boolean hasUserId();
    /**
     * <code>required string userId = 3;</code>
     *
     * <pre>
     *用户Id
     * </pre>
     */
    java.lang.String getUserId();
    /**
     * <code>required string userId = 3;</code>
     *
     * <pre>
     *用户Id
     * </pre>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    // required uint32 ptoNum = 4;
    /**
     * <code>required uint32 ptoNum = 4;</code>
     *
     * <pre>
     *协议类型码
     * </pre>
     */
    boolean hasPtoNum();
    /**
     * <code>required uint32 ptoNum = 4;</code>
     *
     * <pre>
     *协议类型码
     * </pre>
     */
    int getPtoNum();

    // required bytes msg = 5;
    /**
     * <code>required bytes msg = 5;</code>
     *
     * <pre>
     *协议消息的字节流
     * </pre>
     */
    boolean hasMsg();
    /**
     * <code>required bytes msg = 5;</code>
     *
     * <pre>
     *协议消息的字节流
     * </pre>
     */
    com.google.protobuf.ByteString getMsg();
  }
  /**
   * Protobuf type {@code GTransfer}
   *
   * <pre>
   *服务器间的中转协议
   * </pre>
   */
  public static final class GTransfer extends
      com.google.protobuf.GeneratedMessage
      implements GTransferOrBuilder {
    // Use GTransfer.newBuilder() to construct.
    private GTransfer(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GTransfer(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GTransfer defaultInstance;
    public static GTransfer getDefaultInstance() {
      return defaultInstance;
    }

    public GTransfer getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GTransfer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.tao.protobuf.message.internal.Internal.DestType value = com.tao.protobuf.message.internal.Internal.DestType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                dest_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              netId_ = input.readUInt64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              userId_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              ptoNum_ = input.readUInt32();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              msg_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tao.protobuf.message.internal.Internal.internal_static_GTransfer_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tao.protobuf.message.internal.Internal.internal_static_GTransfer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tao.protobuf.message.internal.Internal.GTransfer.class, com.tao.protobuf.message.internal.Internal.GTransfer.Builder.class);
    }

    public static com.google.protobuf.Parser<GTransfer> PARSER =
        new com.google.protobuf.AbstractParser<GTransfer>() {
      public GTransfer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GTransfer(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GTransfer> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .DestType dest = 1;
    public static final int DEST_FIELD_NUMBER = 1;
    private com.tao.protobuf.message.internal.Internal.DestType dest_;
    /**
     * <code>required .DestType dest = 1;</code>
     *
     * <pre>
     *目的地
     * </pre>
     */
    public boolean hasDest() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .DestType dest = 1;</code>
     *
     * <pre>
     *目的地
     * </pre>
     */
    public com.tao.protobuf.message.internal.Internal.DestType getDest() {
      return dest_;
    }

    // optional uint64 netId = 2;
    public static final int NETID_FIELD_NUMBER = 2;
    private long netId_;
    /**
     * <code>optional uint64 netId = 2;</code>
     *
     * <pre>
     *全局唯一netId
     * </pre>
     */
    public boolean hasNetId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint64 netId = 2;</code>
     *
     * <pre>
     *全局唯一netId
     * </pre>
     */
    public long getNetId() {
      return netId_;
    }

    // required string userId = 3;
    public static final int USERID_FIELD_NUMBER = 3;
    private java.lang.Object userId_;
    /**
     * <code>required string userId = 3;</code>
     *
     * <pre>
     *用户Id
     * </pre>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string userId = 3;</code>
     *
     * <pre>
     *用户Id
     * </pre>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string userId = 3;</code>
     *
     * <pre>
     *用户Id
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required uint32 ptoNum = 4;
    public static final int PTONUM_FIELD_NUMBER = 4;
    private int ptoNum_;
    /**
     * <code>required uint32 ptoNum = 4;</code>
     *
     * <pre>
     *协议类型码
     * </pre>
     */
    public boolean hasPtoNum() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required uint32 ptoNum = 4;</code>
     *
     * <pre>
     *协议类型码
     * </pre>
     */
    public int getPtoNum() {
      return ptoNum_;
    }

    // required bytes msg = 5;
    public static final int MSG_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString msg_;
    /**
     * <code>required bytes msg = 5;</code>
     *
     * <pre>
     *协议消息的字节流
     * </pre>
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required bytes msg = 5;</code>
     *
     * <pre>
     *协议消息的字节流
     * </pre>
     */
    public com.google.protobuf.ByteString getMsg() {
      return msg_;
    }

    private void initFields() {
      dest_ = com.tao.protobuf.message.internal.Internal.DestType.Client;
      netId_ = 0L;
      userId_ = "";
      ptoNum_ = 0;
      msg_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasDest()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPtoNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, dest_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, netId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getUserIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, ptoNum_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, msg_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, dest_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, netId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getUserIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, ptoNum_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, msg_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.tao.protobuf.message.internal.Internal.GTransfer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tao.protobuf.message.internal.Internal.GTransfer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tao.protobuf.message.internal.Internal.GTransfer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tao.protobuf.message.internal.Internal.GTransfer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tao.protobuf.message.internal.Internal.GTransfer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tao.protobuf.message.internal.Internal.GTransfer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.tao.protobuf.message.internal.Internal.GTransfer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.tao.protobuf.message.internal.Internal.GTransfer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.tao.protobuf.message.internal.Internal.GTransfer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tao.protobuf.message.internal.Internal.GTransfer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tao.protobuf.message.internal.Internal.GTransfer prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GTransfer}
     *
     * <pre>
     *服务器间的中转协议
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.tao.protobuf.message.internal.Internal.GTransferOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tao.protobuf.message.internal.Internal.internal_static_GTransfer_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tao.protobuf.message.internal.Internal.internal_static_GTransfer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tao.protobuf.message.internal.Internal.GTransfer.class, com.tao.protobuf.message.internal.Internal.GTransfer.Builder.class);
      }

      // Construct using com.tao.protobuf.message.internal.Internal.GTransfer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        dest_ = com.tao.protobuf.message.internal.Internal.DestType.Client;
        bitField0_ = (bitField0_ & ~0x00000001);
        netId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        userId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        ptoNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        msg_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tao.protobuf.message.internal.Internal.internal_static_GTransfer_descriptor;
      }

      public com.tao.protobuf.message.internal.Internal.GTransfer getDefaultInstanceForType() {
        return com.tao.protobuf.message.internal.Internal.GTransfer.getDefaultInstance();
      }

      public com.tao.protobuf.message.internal.Internal.GTransfer build() {
        com.tao.protobuf.message.internal.Internal.GTransfer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tao.protobuf.message.internal.Internal.GTransfer buildPartial() {
        com.tao.protobuf.message.internal.Internal.GTransfer result = new com.tao.protobuf.message.internal.Internal.GTransfer(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.dest_ = dest_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.netId_ = netId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.ptoNum_ = ptoNum_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.msg_ = msg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tao.protobuf.message.internal.Internal.GTransfer) {
          return mergeFrom((com.tao.protobuf.message.internal.Internal.GTransfer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tao.protobuf.message.internal.Internal.GTransfer other) {
        if (other == com.tao.protobuf.message.internal.Internal.GTransfer.getDefaultInstance()) return this;
        if (other.hasDest()) {
          setDest(other.getDest());
        }
        if (other.hasNetId()) {
          setNetId(other.getNetId());
        }
        if (other.hasUserId()) {
          bitField0_ |= 0x00000004;
          userId_ = other.userId_;
          onChanged();
        }
        if (other.hasPtoNum()) {
          setPtoNum(other.getPtoNum());
        }
        if (other.hasMsg()) {
          setMsg(other.getMsg());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDest()) {
          
          return false;
        }
        if (!hasUserId()) {
          
          return false;
        }
        if (!hasPtoNum()) {
          
          return false;
        }
        if (!hasMsg()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tao.protobuf.message.internal.Internal.GTransfer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tao.protobuf.message.internal.Internal.GTransfer) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .DestType dest = 1;
      private com.tao.protobuf.message.internal.Internal.DestType dest_ = com.tao.protobuf.message.internal.Internal.DestType.Client;
      /**
       * <code>required .DestType dest = 1;</code>
       *
       * <pre>
       *目的地
       * </pre>
       */
      public boolean hasDest() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .DestType dest = 1;</code>
       *
       * <pre>
       *目的地
       * </pre>
       */
      public com.tao.protobuf.message.internal.Internal.DestType getDest() {
        return dest_;
      }
      /**
       * <code>required .DestType dest = 1;</code>
       *
       * <pre>
       *目的地
       * </pre>
       */
      public Builder setDest(com.tao.protobuf.message.internal.Internal.DestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        dest_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .DestType dest = 1;</code>
       *
       * <pre>
       *目的地
       * </pre>
       */
      public Builder clearDest() {
        bitField0_ = (bitField0_ & ~0x00000001);
        dest_ = com.tao.protobuf.message.internal.Internal.DestType.Client;
        onChanged();
        return this;
      }

      // optional uint64 netId = 2;
      private long netId_ ;
      /**
       * <code>optional uint64 netId = 2;</code>
       *
       * <pre>
       *全局唯一netId
       * </pre>
       */
      public boolean hasNetId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint64 netId = 2;</code>
       *
       * <pre>
       *全局唯一netId
       * </pre>
       */
      public long getNetId() {
        return netId_;
      }
      /**
       * <code>optional uint64 netId = 2;</code>
       *
       * <pre>
       *全局唯一netId
       * </pre>
       */
      public Builder setNetId(long value) {
        bitField0_ |= 0x00000002;
        netId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 netId = 2;</code>
       *
       * <pre>
       *全局唯一netId
       * </pre>
       */
      public Builder clearNetId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        netId_ = 0L;
        onChanged();
        return this;
      }

      // required string userId = 3;
      private java.lang.Object userId_ = "";
      /**
       * <code>required string userId = 3;</code>
       *
       * <pre>
       *用户Id
       * </pre>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string userId = 3;</code>
       *
       * <pre>
       *用户Id
       * </pre>
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string userId = 3;</code>
       *
       * <pre>
       *用户Id
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string userId = 3;</code>
       *
       * <pre>
       *用户Id
       * </pre>
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string userId = 3;</code>
       *
       * <pre>
       *用户Id
       * </pre>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>required string userId = 3;</code>
       *
       * <pre>
       *用户Id
       * </pre>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        userId_ = value;
        onChanged();
        return this;
      }

      // required uint32 ptoNum = 4;
      private int ptoNum_ ;
      /**
       * <code>required uint32 ptoNum = 4;</code>
       *
       * <pre>
       *协议类型码
       * </pre>
       */
      public boolean hasPtoNum() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required uint32 ptoNum = 4;</code>
       *
       * <pre>
       *协议类型码
       * </pre>
       */
      public int getPtoNum() {
        return ptoNum_;
      }
      /**
       * <code>required uint32 ptoNum = 4;</code>
       *
       * <pre>
       *协议类型码
       * </pre>
       */
      public Builder setPtoNum(int value) {
        bitField0_ |= 0x00000008;
        ptoNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 ptoNum = 4;</code>
       *
       * <pre>
       *协议类型码
       * </pre>
       */
      public Builder clearPtoNum() {
        bitField0_ = (bitField0_ & ~0x00000008);
        ptoNum_ = 0;
        onChanged();
        return this;
      }

      // required bytes msg = 5;
      private com.google.protobuf.ByteString msg_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes msg = 5;</code>
       *
       * <pre>
       *协议消息的字节流
       * </pre>
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required bytes msg = 5;</code>
       *
       * <pre>
       *协议消息的字节流
       * </pre>
       */
      public com.google.protobuf.ByteString getMsg() {
        return msg_;
      }
      /**
       * <code>required bytes msg = 5;</code>
       *
       * <pre>
       *协议消息的字节流
       * </pre>
       */
      public Builder setMsg(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes msg = 5;</code>
       *
       * <pre>
       *协议消息的字节流
       * </pre>
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000010);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:GTransfer)
    }

    static {
      defaultInstance = new GTransfer(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:GTransfer)
  }

  public interface GreetOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .Greet.From from = 1;
    /**
     * <code>required .Greet.From from = 1;</code>
     */
    boolean hasFrom();
    /**
     * <code>required .Greet.From from = 1;</code>
     */
    com.tao.protobuf.message.internal.Internal.Greet.From getFrom();
  }
  /**
   * Protobuf type {@code Greet}
   *
   * <pre>
   *服务间建立连接时发送的协议
   * </pre>
   */
  public static final class Greet extends
      com.google.protobuf.GeneratedMessage
      implements GreetOrBuilder {
    // Use Greet.newBuilder() to construct.
    private Greet(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Greet(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Greet defaultInstance;
    public static Greet getDefaultInstance() {
      return defaultInstance;
    }

    public Greet getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Greet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.tao.protobuf.message.internal.Internal.Greet.From value = com.tao.protobuf.message.internal.Internal.Greet.From.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                from_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tao.protobuf.message.internal.Internal.internal_static_Greet_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tao.protobuf.message.internal.Internal.internal_static_Greet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tao.protobuf.message.internal.Internal.Greet.class, com.tao.protobuf.message.internal.Internal.Greet.Builder.class);
    }

    public static com.google.protobuf.Parser<Greet> PARSER =
        new com.google.protobuf.AbstractParser<Greet>() {
      public Greet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Greet(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Greet> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code Greet.From}
     */
    public enum From
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>Gate = 1;</code>
       */
      Gate(0, 1),
      /**
       * <code>Auth = 2;</code>
       */
      Auth(1, 2),
      /**
       * <code>Logic = 3;</code>
       */
      Logic(2, 3),
      ;

      /**
       * <code>Gate = 1;</code>
       */
      public static final int Gate_VALUE = 1;
      /**
       * <code>Auth = 2;</code>
       */
      public static final int Auth_VALUE = 2;
      /**
       * <code>Logic = 3;</code>
       */
      public static final int Logic_VALUE = 3;


      public final int getNumber() { return value; }

      public static From valueOf(int value) {
        switch (value) {
          case 1: return Gate;
          case 2: return Auth;
          case 3: return Logic;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<From>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<From>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<From>() {
              public From findValueByNumber(int number) {
                return From.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.tao.protobuf.message.internal.Internal.Greet.getDescriptor().getEnumTypes().get(0);
      }

      private static final From[] VALUES = values();

      public static From valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private From(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Greet.From)
    }

    private int bitField0_;
    // required .Greet.From from = 1;
    public static final int FROM_FIELD_NUMBER = 1;
    private com.tao.protobuf.message.internal.Internal.Greet.From from_;
    /**
     * <code>required .Greet.From from = 1;</code>
     */
    public boolean hasFrom() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .Greet.From from = 1;</code>
     */
    public com.tao.protobuf.message.internal.Internal.Greet.From getFrom() {
      return from_;
    }

    private void initFields() {
      from_ = com.tao.protobuf.message.internal.Internal.Greet.From.Gate;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasFrom()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, from_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, from_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.tao.protobuf.message.internal.Internal.Greet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tao.protobuf.message.internal.Internal.Greet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tao.protobuf.message.internal.Internal.Greet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tao.protobuf.message.internal.Internal.Greet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tao.protobuf.message.internal.Internal.Greet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tao.protobuf.message.internal.Internal.Greet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.tao.protobuf.message.internal.Internal.Greet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.tao.protobuf.message.internal.Internal.Greet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.tao.protobuf.message.internal.Internal.Greet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tao.protobuf.message.internal.Internal.Greet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tao.protobuf.message.internal.Internal.Greet prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Greet}
     *
     * <pre>
     *服务间建立连接时发送的协议
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.tao.protobuf.message.internal.Internal.GreetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tao.protobuf.message.internal.Internal.internal_static_Greet_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tao.protobuf.message.internal.Internal.internal_static_Greet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tao.protobuf.message.internal.Internal.Greet.class, com.tao.protobuf.message.internal.Internal.Greet.Builder.class);
      }

      // Construct using com.tao.protobuf.message.internal.Internal.Greet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        from_ = com.tao.protobuf.message.internal.Internal.Greet.From.Gate;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tao.protobuf.message.internal.Internal.internal_static_Greet_descriptor;
      }

      public com.tao.protobuf.message.internal.Internal.Greet getDefaultInstanceForType() {
        return com.tao.protobuf.message.internal.Internal.Greet.getDefaultInstance();
      }

      public com.tao.protobuf.message.internal.Internal.Greet build() {
        com.tao.protobuf.message.internal.Internal.Greet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tao.protobuf.message.internal.Internal.Greet buildPartial() {
        com.tao.protobuf.message.internal.Internal.Greet result = new com.tao.protobuf.message.internal.Internal.Greet(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.from_ = from_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tao.protobuf.message.internal.Internal.Greet) {
          return mergeFrom((com.tao.protobuf.message.internal.Internal.Greet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tao.protobuf.message.internal.Internal.Greet other) {
        if (other == com.tao.protobuf.message.internal.Internal.Greet.getDefaultInstance()) return this;
        if (other.hasFrom()) {
          setFrom(other.getFrom());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFrom()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tao.protobuf.message.internal.Internal.Greet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tao.protobuf.message.internal.Internal.Greet) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .Greet.From from = 1;
      private com.tao.protobuf.message.internal.Internal.Greet.From from_ = com.tao.protobuf.message.internal.Internal.Greet.From.Gate;
      /**
       * <code>required .Greet.From from = 1;</code>
       */
      public boolean hasFrom() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .Greet.From from = 1;</code>
       */
      public com.tao.protobuf.message.internal.Internal.Greet.From getFrom() {
        return from_;
      }
      /**
       * <code>required .Greet.From from = 1;</code>
       */
      public Builder setFrom(com.tao.protobuf.message.internal.Internal.Greet.From value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        from_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .Greet.From from = 1;</code>
       */
      public Builder clearFrom() {
        bitField0_ = (bitField0_ & ~0x00000001);
        from_ = com.tao.protobuf.message.internal.Internal.Greet.From.Gate;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Greet)
    }

    static {
      defaultInstance = new Greet(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Greet)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_GTransfer_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GTransfer_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Greet_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Greet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016internal.proto\"`\n\tGTransfer\022\027\n\004dest\030\001 " +
      "\002(\0162\t.DestType\022\r\n\005netId\030\002 \001(\004\022\016\n\006userId\030" +
      "\003 \002(\t\022\016\n\006ptoNum\030\004 \002(\r\022\013\n\003msg\030\005 \002(\014\"I\n\005Gr" +
      "eet\022\031\n\004from\030\001 \002(\0162\013.Greet.From\"%\n\004From\022\010" +
      "\n\004Gate\020\001\022\010\n\004Auth\020\002\022\t\n\005Logic\020\003*5\n\010DestTyp" +
      "e\022\n\n\006Client\020\001\022\010\n\004Gate\020\002\022\010\n\004Auth\020\003\022\t\n\005Log" +
      "ic\020\004B-\n!com.tao.protobuf.message.interna" +
      "lB\010Internal"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_GTransfer_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_GTransfer_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_GTransfer_descriptor,
              new java.lang.String[] { "Dest", "NetId", "UserId", "PtoNum", "Msg", });
          internal_static_Greet_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Greet_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Greet_descriptor,
              new java.lang.String[] { "From", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
