// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.tao.protobuf.message.client2server.chat;

public final class Chat {
  private Chat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CChatMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string senderId = 1;
    /**
     * <code>required string senderId = 1;</code>
     *
     * <pre>
     *消息发送者的userId
     * </pre>
     */
    boolean hasSenderId();
    /**
     * <code>required string senderId = 1;</code>
     *
     * <pre>
     *消息发送者的userId
     * </pre>
     */
    java.lang.String getSenderId();
    /**
     * <code>required string senderId = 1;</code>
     *
     * <pre>
     *消息发送者的userId
     * </pre>
     */
    com.google.protobuf.ByteString
        getSenderIdBytes();

    // required string receiverId = 2;
    /**
     * <code>required string receiverId = 2;</code>
     *
     * <pre>
     *消息接收者的userId
     * </pre>
     */
    boolean hasReceiverId();
    /**
     * <code>required string receiverId = 2;</code>
     *
     * <pre>
     *消息接收者的userId
     * </pre>
     */
    java.lang.String getReceiverId();
    /**
     * <code>required string receiverId = 2;</code>
     *
     * <pre>
     *消息接收者的userId
     * </pre>
     */
    com.google.protobuf.ByteString
        getReceiverIdBytes();

    // required string content = 3;
    /**
     * <code>required string content = 3;</code>
     *
     * <pre>
     *消息内容
     * </pre>
     */
    boolean hasContent();
    /**
     * <code>required string content = 3;</code>
     *
     * <pre>
     *消息内容
     * </pre>
     */
    java.lang.String getContent();
    /**
     * <code>required string content = 3;</code>
     *
     * <pre>
     *消息内容
     * </pre>
     */
    com.google.protobuf.ByteString
        getContentBytes();
  }
  /**
   * Protobuf type {@code CChatMsg}
   *
   * <pre>
   *
   *客户端聊天消息类
   * </pre>
   */
  public static final class CChatMsg extends
      com.google.protobuf.GeneratedMessage
      implements CChatMsgOrBuilder {
    // Use CChatMsg.newBuilder() to construct.
    private CChatMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CChatMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CChatMsg defaultInstance;
    public static CChatMsg getDefaultInstance() {
      return defaultInstance;
    }

    public CChatMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CChatMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              senderId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              receiverId_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              content_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tao.protobuf.message.client2server.chat.Chat.internal_static_CChatMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tao.protobuf.message.client2server.chat.Chat.internal_static_CChatMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tao.protobuf.message.client2server.chat.Chat.CChatMsg.class, com.tao.protobuf.message.client2server.chat.Chat.CChatMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<CChatMsg> PARSER =
        new com.google.protobuf.AbstractParser<CChatMsg>() {
      public CChatMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CChatMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CChatMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string senderId = 1;
    public static final int SENDERID_FIELD_NUMBER = 1;
    private java.lang.Object senderId_;
    /**
     * <code>required string senderId = 1;</code>
     *
     * <pre>
     *消息发送者的userId
     * </pre>
     */
    public boolean hasSenderId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string senderId = 1;</code>
     *
     * <pre>
     *消息发送者的userId
     * </pre>
     */
    public java.lang.String getSenderId() {
      java.lang.Object ref = senderId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          senderId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string senderId = 1;</code>
     *
     * <pre>
     *消息发送者的userId
     * </pre>
     */
    public com.google.protobuf.ByteString
        getSenderIdBytes() {
      java.lang.Object ref = senderId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string receiverId = 2;
    public static final int RECEIVERID_FIELD_NUMBER = 2;
    private java.lang.Object receiverId_;
    /**
     * <code>required string receiverId = 2;</code>
     *
     * <pre>
     *消息接收者的userId
     * </pre>
     */
    public boolean hasReceiverId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string receiverId = 2;</code>
     *
     * <pre>
     *消息接收者的userId
     * </pre>
     */
    public java.lang.String getReceiverId() {
      java.lang.Object ref = receiverId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          receiverId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string receiverId = 2;</code>
     *
     * <pre>
     *消息接收者的userId
     * </pre>
     */
    public com.google.protobuf.ByteString
        getReceiverIdBytes() {
      java.lang.Object ref = receiverId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiverId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string content = 3;
    public static final int CONTENT_FIELD_NUMBER = 3;
    private java.lang.Object content_;
    /**
     * <code>required string content = 3;</code>
     *
     * <pre>
     *消息内容
     * </pre>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string content = 3;</code>
     *
     * <pre>
     *消息内容
     * </pre>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          content_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string content = 3;</code>
     *
     * <pre>
     *消息内容
     * </pre>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      senderId_ = "";
      receiverId_ = "";
      content_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSenderId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReceiverId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSenderIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getReceiverIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getContentBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSenderIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getReceiverIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getContentBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.tao.protobuf.message.client2server.chat.Chat.CChatMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tao.protobuf.message.client2server.chat.Chat.CChatMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tao.protobuf.message.client2server.chat.Chat.CChatMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tao.protobuf.message.client2server.chat.Chat.CChatMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tao.protobuf.message.client2server.chat.Chat.CChatMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tao.protobuf.message.client2server.chat.Chat.CChatMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.tao.protobuf.message.client2server.chat.Chat.CChatMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.tao.protobuf.message.client2server.chat.Chat.CChatMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.tao.protobuf.message.client2server.chat.Chat.CChatMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tao.protobuf.message.client2server.chat.Chat.CChatMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tao.protobuf.message.client2server.chat.Chat.CChatMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CChatMsg}
     *
     * <pre>
     *
     *客户端聊天消息类
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.tao.protobuf.message.client2server.chat.Chat.CChatMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tao.protobuf.message.client2server.chat.Chat.internal_static_CChatMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tao.protobuf.message.client2server.chat.Chat.internal_static_CChatMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tao.protobuf.message.client2server.chat.Chat.CChatMsg.class, com.tao.protobuf.message.client2server.chat.Chat.CChatMsg.Builder.class);
      }

      // Construct using com.tao.protobuf.message.client2server.chat.Chat.CChatMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        senderId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        receiverId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tao.protobuf.message.client2server.chat.Chat.internal_static_CChatMsg_descriptor;
      }

      public com.tao.protobuf.message.client2server.chat.Chat.CChatMsg getDefaultInstanceForType() {
        return com.tao.protobuf.message.client2server.chat.Chat.CChatMsg.getDefaultInstance();
      }

      public com.tao.protobuf.message.client2server.chat.Chat.CChatMsg build() {
        com.tao.protobuf.message.client2server.chat.Chat.CChatMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tao.protobuf.message.client2server.chat.Chat.CChatMsg buildPartial() {
        com.tao.protobuf.message.client2server.chat.Chat.CChatMsg result = new com.tao.protobuf.message.client2server.chat.Chat.CChatMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.senderId_ = senderId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.receiverId_ = receiverId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.content_ = content_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tao.protobuf.message.client2server.chat.Chat.CChatMsg) {
          return mergeFrom((com.tao.protobuf.message.client2server.chat.Chat.CChatMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tao.protobuf.message.client2server.chat.Chat.CChatMsg other) {
        if (other == com.tao.protobuf.message.client2server.chat.Chat.CChatMsg.getDefaultInstance()) return this;
        if (other.hasSenderId()) {
          bitField0_ |= 0x00000001;
          senderId_ = other.senderId_;
          onChanged();
        }
        if (other.hasReceiverId()) {
          bitField0_ |= 0x00000002;
          receiverId_ = other.receiverId_;
          onChanged();
        }
        if (other.hasContent()) {
          bitField0_ |= 0x00000004;
          content_ = other.content_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSenderId()) {
          
          return false;
        }
        if (!hasReceiverId()) {
          
          return false;
        }
        if (!hasContent()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tao.protobuf.message.client2server.chat.Chat.CChatMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tao.protobuf.message.client2server.chat.Chat.CChatMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string senderId = 1;
      private java.lang.Object senderId_ = "";
      /**
       * <code>required string senderId = 1;</code>
       *
       * <pre>
       *消息发送者的userId
       * </pre>
       */
      public boolean hasSenderId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string senderId = 1;</code>
       *
       * <pre>
       *消息发送者的userId
       * </pre>
       */
      public java.lang.String getSenderId() {
        java.lang.Object ref = senderId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          senderId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string senderId = 1;</code>
       *
       * <pre>
       *消息发送者的userId
       * </pre>
       */
      public com.google.protobuf.ByteString
          getSenderIdBytes() {
        java.lang.Object ref = senderId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          senderId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string senderId = 1;</code>
       *
       * <pre>
       *消息发送者的userId
       * </pre>
       */
      public Builder setSenderId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        senderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string senderId = 1;</code>
       *
       * <pre>
       *消息发送者的userId
       * </pre>
       */
      public Builder clearSenderId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        senderId_ = getDefaultInstance().getSenderId();
        onChanged();
        return this;
      }
      /**
       * <code>required string senderId = 1;</code>
       *
       * <pre>
       *消息发送者的userId
       * </pre>
       */
      public Builder setSenderIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        senderId_ = value;
        onChanged();
        return this;
      }

      // required string receiverId = 2;
      private java.lang.Object receiverId_ = "";
      /**
       * <code>required string receiverId = 2;</code>
       *
       * <pre>
       *消息接收者的userId
       * </pre>
       */
      public boolean hasReceiverId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string receiverId = 2;</code>
       *
       * <pre>
       *消息接收者的userId
       * </pre>
       */
      public java.lang.String getReceiverId() {
        java.lang.Object ref = receiverId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          receiverId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string receiverId = 2;</code>
       *
       * <pre>
       *消息接收者的userId
       * </pre>
       */
      public com.google.protobuf.ByteString
          getReceiverIdBytes() {
        java.lang.Object ref = receiverId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receiverId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string receiverId = 2;</code>
       *
       * <pre>
       *消息接收者的userId
       * </pre>
       */
      public Builder setReceiverId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        receiverId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string receiverId = 2;</code>
       *
       * <pre>
       *消息接收者的userId
       * </pre>
       */
      public Builder clearReceiverId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        receiverId_ = getDefaultInstance().getReceiverId();
        onChanged();
        return this;
      }
      /**
       * <code>required string receiverId = 2;</code>
       *
       * <pre>
       *消息接收者的userId
       * </pre>
       */
      public Builder setReceiverIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        receiverId_ = value;
        onChanged();
        return this;
      }

      // required string content = 3;
      private java.lang.Object content_ = "";
      /**
       * <code>required string content = 3;</code>
       *
       * <pre>
       *消息内容
       * </pre>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string content = 3;</code>
       *
       * <pre>
       *消息内容
       * </pre>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string content = 3;</code>
       *
       * <pre>
       *消息内容
       * </pre>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string content = 3;</code>
       *
       * <pre>
       *消息内容
       * </pre>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string content = 3;</code>
       *
       * <pre>
       *消息内容
       * </pre>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000004);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>required string content = 3;</code>
       *
       * <pre>
       *消息内容
       * </pre>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        content_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CChatMsg)
    }

    static {
      defaultInstance = new CChatMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CChatMsg)
  }

  public interface SChatMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string content = 1;
    /**
     * <code>required string content = 1;</code>
     *
     * <pre>
     *消息内容
     * </pre>
     */
    boolean hasContent();
    /**
     * <code>required string content = 1;</code>
     *
     * <pre>
     *消息内容
     * </pre>
     */
    java.lang.String getContent();
    /**
     * <code>required string content = 1;</code>
     *
     * <pre>
     *消息内容
     * </pre>
     */
    com.google.protobuf.ByteString
        getContentBytes();
  }
  /**
   * Protobuf type {@code SChatMsg}
   *
   * <pre>
   *
   *服务器之间的消息体
   * </pre>
   */
  public static final class SChatMsg extends
      com.google.protobuf.GeneratedMessage
      implements SChatMsgOrBuilder {
    // Use SChatMsg.newBuilder() to construct.
    private SChatMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SChatMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SChatMsg defaultInstance;
    public static SChatMsg getDefaultInstance() {
      return defaultInstance;
    }

    public SChatMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SChatMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              content_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tao.protobuf.message.client2server.chat.Chat.internal_static_SChatMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tao.protobuf.message.client2server.chat.Chat.internal_static_SChatMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tao.protobuf.message.client2server.chat.Chat.SChatMsg.class, com.tao.protobuf.message.client2server.chat.Chat.SChatMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<SChatMsg> PARSER =
        new com.google.protobuf.AbstractParser<SChatMsg>() {
      public SChatMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SChatMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SChatMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string content = 1;
    public static final int CONTENT_FIELD_NUMBER = 1;
    private java.lang.Object content_;
    /**
     * <code>required string content = 1;</code>
     *
     * <pre>
     *消息内容
     * </pre>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string content = 1;</code>
     *
     * <pre>
     *消息内容
     * </pre>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          content_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string content = 1;</code>
     *
     * <pre>
     *消息内容
     * </pre>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      content_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasContent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getContentBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getContentBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.tao.protobuf.message.client2server.chat.Chat.SChatMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tao.protobuf.message.client2server.chat.Chat.SChatMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tao.protobuf.message.client2server.chat.Chat.SChatMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tao.protobuf.message.client2server.chat.Chat.SChatMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tao.protobuf.message.client2server.chat.Chat.SChatMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tao.protobuf.message.client2server.chat.Chat.SChatMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.tao.protobuf.message.client2server.chat.Chat.SChatMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.tao.protobuf.message.client2server.chat.Chat.SChatMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.tao.protobuf.message.client2server.chat.Chat.SChatMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tao.protobuf.message.client2server.chat.Chat.SChatMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tao.protobuf.message.client2server.chat.Chat.SChatMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SChatMsg}
     *
     * <pre>
     *
     *服务器之间的消息体
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.tao.protobuf.message.client2server.chat.Chat.SChatMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tao.protobuf.message.client2server.chat.Chat.internal_static_SChatMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tao.protobuf.message.client2server.chat.Chat.internal_static_SChatMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tao.protobuf.message.client2server.chat.Chat.SChatMsg.class, com.tao.protobuf.message.client2server.chat.Chat.SChatMsg.Builder.class);
      }

      // Construct using com.tao.protobuf.message.client2server.chat.Chat.SChatMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tao.protobuf.message.client2server.chat.Chat.internal_static_SChatMsg_descriptor;
      }

      public com.tao.protobuf.message.client2server.chat.Chat.SChatMsg getDefaultInstanceForType() {
        return com.tao.protobuf.message.client2server.chat.Chat.SChatMsg.getDefaultInstance();
      }

      public com.tao.protobuf.message.client2server.chat.Chat.SChatMsg build() {
        com.tao.protobuf.message.client2server.chat.Chat.SChatMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tao.protobuf.message.client2server.chat.Chat.SChatMsg buildPartial() {
        com.tao.protobuf.message.client2server.chat.Chat.SChatMsg result = new com.tao.protobuf.message.client2server.chat.Chat.SChatMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.content_ = content_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tao.protobuf.message.client2server.chat.Chat.SChatMsg) {
          return mergeFrom((com.tao.protobuf.message.client2server.chat.Chat.SChatMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tao.protobuf.message.client2server.chat.Chat.SChatMsg other) {
        if (other == com.tao.protobuf.message.client2server.chat.Chat.SChatMsg.getDefaultInstance()) return this;
        if (other.hasContent()) {
          bitField0_ |= 0x00000001;
          content_ = other.content_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasContent()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tao.protobuf.message.client2server.chat.Chat.SChatMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tao.protobuf.message.client2server.chat.Chat.SChatMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string content = 1;
      private java.lang.Object content_ = "";
      /**
       * <code>required string content = 1;</code>
       *
       * <pre>
       *消息内容
       * </pre>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string content = 1;</code>
       *
       * <pre>
       *消息内容
       * </pre>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string content = 1;</code>
       *
       * <pre>
       *消息内容
       * </pre>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string content = 1;</code>
       *
       * <pre>
       *消息内容
       * </pre>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string content = 1;</code>
       *
       * <pre>
       *消息内容
       * </pre>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000001);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>required string content = 1;</code>
       *
       * <pre>
       *消息内容
       * </pre>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        content_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SChatMsg)
    }

    static {
      defaultInstance = new SChatMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SChatMsg)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CChatMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CChatMsg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SChatMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SChatMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nchat.proto\"A\n\010CChatMsg\022\020\n\010senderId\030\001 \002" +
      "(\t\022\022\n\nreceiverId\030\002 \002(\t\022\017\n\007content\030\003 \002(\t\"" +
      "\033\n\010SChatMsg\022\017\n\007content\030\001 \002(\tB3\n+com.tao." +
      "protobuf.message.client2server.chatB\004Cha" +
      "t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_CChatMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_CChatMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CChatMsg_descriptor,
              new java.lang.String[] { "SenderId", "ReceiverId", "Content", });
          internal_static_SChatMsg_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_SChatMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SChatMsg_descriptor,
              new java.lang.String[] { "Content", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
